description: "Is NLQ Agent Prompt"
providers: [openai:gpt-4-1106-preview, openai:gpt-3.5-turbo-1106]

defaultTest:
  assert:
    - type: is-json
      value: 
        required: [rank, passable]
        type: object
        properties:
          rank:
            type: number
          passable:
            type: boolean

prompts: prompt.txt
tests: test*.yaml